import { Roboto,Playwrite_AU_VIC } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";


const geistSans = Roboto({
  variable: "--font-geist-sans",
  subsets: ["latin"],weight: "700",
});
const geistSanss = Playwrite_AU_VIC({
  variable: "--font-geist-sanss",
  subsets: ["latin"],weight: "400",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistSanss.variable} antialiased`}
        >
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
